name: Auto Assign PRs

on:
  pull_request:
    types: [opened, reopened]

  workflow_dispatch:
jobs:
  assignee:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_assignee.yml@master
<<<<<<< HEAD
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      assignees: 'clouddrove-ci'
=======

    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      assignees: 'clouddrove-ci'
>>>>>>> feat/amazon-mq
