name: changelog
permissions: write-all
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  changelog:
    uses: clouddrove/github-shared-workflows/.github/workflows/changelog.yml@master
<<<<<<< HEAD
    secrets: inherit
    with:
      branch: 'master'
=======

    secrets: inherit
    with:
      branch: 'master'
>>>>>>> feat/amazon-mq
