<<<<<<< HEAD
name: 'Create README.md file'
=======
name: readme workflow
>>>>>>> feat/amazon-mq
on:
  push:
    branches:
      - master
<<<<<<< HEAD

jobs:
  readme:
    name: 'readme-create'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Set up Python 3.7'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 'create readme'
        uses: 'clouddrove/github-actions@9.0.3'
        with:
          actions_subcommand: 'readme'
          github_token: '${{ secrets.GITHUB }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: 'pre-commit check errors'
        uses: pre-commit/action@v3.0.0
        continue-on-error: true

      - name: 'pre-commit fix erros'
        uses: pre-commit/action@v3.0.0
        continue-on-error: true

      - name: 'push readme'
        uses: 'clouddrove/github-actions@9.0.3'
        continue-on-error: true
        with:
          actions_subcommand: 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }} # required
        if: always()
=======
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
jobs:
  readme:
    uses: clouddrove/github-shared-workflows/.github/workflows/readme.yml@master
    secrets:
      TOKEN : ${{ secrets.GITHUB }}
      SLACK_WEBHOOK_TERRAFORM: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }}
>>>>>>> feat/amazon-mq
